### ISSUE TITLE
Add new modules and their related resources 

### ISSUE THREAD

**Issue by TammyTee** [tighten/onramp#377]
Here is a list of new modules we'd like to add to Onramp. 
Before we publish these, let's ensure we have assets for each module:

**Todo**

- [x] Get assets for each new module
- [x] Create seeders for each module
- [x] Write descriptions and skills for each module
- [ ] Add modules to prod

## Intermediate
**Auth**
Free audio: 
[The Laravel Podcast - Presets & Jetstream, with Michael Dyrynda](https://laravelpodcast.com/episodes/presets-jetstream-with-michael-dyrynda)

**Laravel Core**
Free audio:
[The Laravel Podcast - The Service Container, with Christoph Rumpel](https://laravelpodcast.com/episodes/the-service-container-with-christoph-rumpel)

**Laravel Queues**
Free audio:
[The Laravel Podcast - Queues, with Mohamed Said](https://laravelpodcast.com/episodes/queues-with-mohamed-said)

---

## Advanced
**Advanced Auth Concepts**

**Laravel Package Development**
Paid video courses:
[Laravel Package Training](https://spatie.be/videos/laravel-package-training)
[PHP Package Development](https://phppackagedevelopment.com/)

Free articles:
[Laravel Package Development](https://laravelpackage.com/)

Free audio:
[The Laravel Podcast - Packages, with Freek Van der Herten & Marcel Pociot](https://laravelpodcast.com/episodes/packages-with-freek-van-der-herten-marcel-pociot)

**Comment by TammyTee** [comment]
@darkboywonder - I think I may have misinterpreted Matt's message when I created this issue. When we first looked at #334  we thought the queues episode should be a part of the Laravel Core module. Do you still think that's the case or do you think we should have an entire module dedicated to queues?

**Comment by TammyTee** [comment]
#### Proposed Descriptions and Skills

| **Module** | **Description** | **Skills** |
| - | - | - |
| Auth | Learn how to verify your application's users and other preventative measures you can take to protect your app against security vulnerabilities. | Authorize user actions, Authenticate users, Manage user roles and permissions |
| Laravel Core | Take your mastery of Laravel to the next level by diving into the internal features at the framework's core. | |
| Laravel Queues | Learn how to create performant Laravel apps by using queues to process your time intensive tasks in the background. | |
| Laravel Package Development | Enhance the functionality of your application by creating extensible packages you can share with the community. | Use Composer, Install Composer, Create an open-source project |
