### ISSUE TITLE
Soft delete expired resources

### ISSUE THREAD

**Issue by TammyTee** [tighten/onramp#475]
**Todo**
- [x] update expired resources to be soft deleted
- [x] hide soft deleted resources from the frontend
- [x] soft deleted resources should show up in the expired resources report

At the time of writing, there is currently 1 expired resource to be soft-deleted and removed from the frontend
- Laracasts Series - Learn Laravel Forge https://laracasts.com/series/learn-laravel-forge
