### ISSUE TITLE
Upgrade to Vue3

### ISSUE THREAD

**Issue by JasonTame** [tighten/onramp#589]
[Vue2 was marked as End of Life on December 31st, 2023. 
](https://v2.vuejs.org/eol/)

Looking through the existing components, it shouldn't be too much work to move to Vue3. There is one dependency that would probably need to be replaced or removed - [vue-notification](https://www.npmjs.com/package/vue-notification). A [fork of the dependency](https://www.npmjs.com/package/@gmirmand/vue-notification) that is compatible with Vue3 is available though.

I'd be happy to work on this if Tighten aren't planning on tackling it already 🫡

**Tasks**
- [ ] Install Vue migration build alongside Vue3
- [ ] Replace deprecated features with Vue3 alternatives
- [ ] Resolve any package incompatibilities
- [ ] Resolve migration build warnings
- [ ] Uninstall migration build

**Comment by MarcyLina** [comment]
Hi @JasonTame !

You must be a psychic because that's very high on my list of to-dos. It would be a huge help if you wanted to help out with that! 😁

**Comment by JasonTame** [comment]
@MarcyLina Great! I'll get started then 😁

**Comment by JasonTame** [comment]
Hi @MarcyLina 

This upgrade is unfortunately trickier than I expected. It will require some refactoring of the UI and potentially replacing some of the dependencies. The main challenges are:

1. The `vue-select` dependency has a 'beta' release which [states it has Vue3 support](https://vue-select.org/guide/upgrading.html), but after following the update steps, it is completely broken. It doesn't look like it's being actively maintained anymore so it's probably best to choose an alternative select field solution or build it in natively. 
2. The way tabs work will need to be completely refactored to use template refs, as the `$children` API [has been removed](https://v3-migration.vuejs.org/breaking-changes/children.html)

There are also a couple smaller things that need to be done, but aren't major blockers:
1. The `capitalize` and `slug` filters will need to be replaced by computed props or methods as [filters have been removed in Vue3 ](https://v3-migration.vuejs.org/breaking-changes/filters.html)
2. The vue-notification dependency needs to be replaced with a Vue3 compatible version. After trying a couple options, [this one](https://github.com/kyvg/vue3-notification) seems to work. I'm not sure if it's being actively maintained anymore though. 

I didn't want to get too deep into solving the above challenges without consulting you, as it would mean making significant changes.

**Comment by MarcyLina** [comment]
Hey @JasonTame

Thank you for looking into this so thoroughly! 

This is quite a heavy lift! Your game plan is thoughtfully considered and sounds great to me as long as we can keep style consistency as close as possible to the current UI. If this is still something you'd like to work on, you have my green light! However, if this seems like more than you would like to take on, I COMPLETELY understand. No pressure, no worries. 😁
